name: Secure CI/CD with Vault

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Install Vault
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y vault

      - name: Start Vault container
        run: |
          docker-compose up -d vault

      - name: Initialize Vault and Fetch secrets
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: root
        run: |
          echo "Initializing Vault..."
          sleep 5  # Wait for Vault container to start
          SECRETS=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/secret/data/myapp | jq -r '.data.data')
          export DB_USER=$(echo $SECRETS | jq -r '.DB_USER')
         
