apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: "cloud_lab3"
            - name: MYSQL_USER
              value: "dshevelev"
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_ROOT_PASSWORD
              value: "0000"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-init-db
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-init-db
          configMap:
            name: init-db-cfg
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-cfg
data:
  init-db.sql: |
    CREATE TABLE test (id INT PRIMARY KEY AUTO_INCREMENT, text VARCHAR(255));
    INSERT INTO test (text) VALUES ('Hello, world! Lab 3 is done again!');