apiVersion: v1
kind: Service
metadata:
 name: nginx-service
 labels:
   app: nginx
spec:
 type: LoadBalancer
 selector:
   app: nginx
 ports:
   - name: metrics
     port: 9113
     targetPort: 9113
   - name: http
     port: 10
     targetPort: 10
     protocol: TCP