apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
   app: nginx
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
    labels:
      app: nginx
   spec:
     containers:
     - name: nginx
       image: nginx:latest
       ports:
       - name: http
         containerPort: 10
     - name: nginx-exporter
       image: nginx/nginx-prometheus-exporter:latest
       args:
         - --nginx.scrape-uri=http://127.0.0.1:1010/metrics
       ports:
        - name: metrics
          containerPort: 9113


